apiVersion: v1
kind: Service
metadata:
  name: sarimax-service
spec:
  type: NodePort  # Use LoadBalancer if you're on a cloud cluster
  selector:
    app: sarimax
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007  # accessible on http://localhost:30007
